import type { SoundVector } from '../../types';

export interface TurtleState {
  pitch: number;
  time: number; // in ms
  duration: number; // in ms
}

/**
 * Interprets a character sequence (usually generated by an L-System)
 * as a series of movements and branches in pitch and time.
 *
 * Commands:
 *   - A, B, F: Play note at current pitch and advance time by duration.
 *   - +: Increase pitch by interval (semitones).
 *   - -: Decrease pitch by interval (semitones).
 *   - [: Push current state (pitch and time) onto stack (branch start).
 *   - ]: Pop state from stack, returning pitch and time to that point (branch end/resolve).
 */
export function interpretTurtleMelody(
  sequence: string,
  basePitch = 60,
  stepSize = 2, // semitones (e.g. 2 for major seconds)
  noteDurationMs = 250, // sixteenth note at 120 bpm
  sourceId = 'lsystem-turtle'
): SoundVector[] {
  const vectors: SoundVector[] = [];
  const stack: Array<{ pitch: number; time: number }> = [];

  const state: TurtleState = {
    pitch: basePitch,
    time: 0,
    duration: noteDurationMs,
  };

  for (let i = 0; i < sequence.length; i++) {
    const char = sequence[i];

    if (char === 'F' || char === 'A' || char === 'B') {
      vectors.push({
        id: `turtle-${i}-${Math.random().toString(36).slice(2, 6)}`,
        t: state.time,
        p: state.pitch,
        duration: state.duration,
        velocity: 0.8,
        sourceId,
      });
      state.time += state.duration;
    } else if (char === '+') {
      state.pitch = Math.max(12, Math.min(127, state.pitch + stepSize));
    } else if (char === '-') {
      state.pitch = Math.max(12, Math.min(127, state.pitch - stepSize));
    } else if (char === '[') {
      stack.push({ pitch: state.pitch, time: state.time });
    } else if (char === ']') {
      const popped = stack.pop();
      if (popped) {
        state.pitch = popped.pitch;
        state.time = popped.time;
      }
    }
  }

  return vectors;
}
